version: '3.8'

services:

  db:
    container_name: db
    image: postgres:latest
    env_file: ./.env
    volumes:
      - db-v:/var/lib/postgresql
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - default-n
    restart: unless-stopped

  backend:
    container_name: backend
    build: ./services/backend
    image: backend_image
    env_file: ./.env
    volumes:
      - backend-v:/code
      - ssl-v:/ssl
    ports:
      - "8000:8000"
    expose:
      - 8000
    networks:
      - default-n
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    container_name: frontend
    build: ./services/frontend
    image: frontend_image
    env_file: ./.env
    volumes:
      - frontend-v:/usr/src/app
      - ssl-v:/ssl
    ports:
      - "3000:3000"
    expose:
      - 3000
    networks:
      - default-n
    restart: unless-stopped

volumes:

  frontend-v:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${PWD}/services/frontend"

  backend-v:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${PWD}/services/backend"

  db-v:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${PWD}/services/postgreSQL"
  
  ssl-v:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${PWD}/ssl"

networks:
  default-n:
    driver: bridge
