version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./services/postgreSQL:/var/lib/postgresql/data
    env_file: .env
  backend:
    build: ./services/backend
    volumes:
      - ./services/backend:/code
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
  frontend:
    build: ./services/frontend
    volumes:
      - ./services/frontend:/usr/src/app
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend